module.exports = {
    MONGOURI: "mongodb+srv://Hema:L0uF0dvrx81udHpb@cluster0.vm6pv.mongodb.net/StudyChain?retryWrites=true&w=majority",
    JWT_SECRET: "aweuiwowfwbfjqqgvytryrtyuodnsfhvwh",
    rpcURL : "https://kovan.infura.io/v3/16497e91567d468facb98a99c27db479",
    private_key : 'a1dd85b68f449a7acbed0f91d9cc586b7b943a9d057ddf6f5327f13204f69e64',
    account : "0x9aa49368F973F32a1d8E9C8D9F58fd203C625BEe",
    abi : [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"string","name":"uid","type":"string"},{"indexed":true,"internalType":"string","name":"role","type":"string"}],"name":"UserAdded","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"string","name":"uid","type":"string"},{"indexed":false,"internalType":"uint64","name":"rating","type":"uint64"}],"name":"UserRateUpdation","type":"event"},{"inputs":[{"internalType":"string","name":"_uid","type":"string"},{"internalType":"string","name":"_name","type":"string"},{"internalType":"string","name":"_location","type":"string"},{"internalType":"string","name":"_status","type":"string"},{"internalType":"uint64","name":"_balance","type":"uint64"}],"name":"addUser","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"_uid","type":"string"}],"name":"checkRating","outputs":[{"internalType":"uint64","name":"","type":"uint64"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"","type":"string"}],"name":"curators","outputs":[{"internalType":"string","name":"uid","type":"string"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"location","type":"string"},{"internalType":"string","name":"status","type":"string"},{"internalType":"uint64","name":"rating","type":"uint64"},{"internalType":"uint64","name":"balance","type":"uint64"},{"internalType":"bool","name":"exists","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"","type":"string"}],"name":"groups","outputs":[{"internalType":"string","name":"uid","type":"string"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"domain","type":"string"},{"internalType":"string","name":"admin","type":"string"},{"internalType":"string","name":"status","type":"string"},{"internalType":"uint64","name":"source","type":"uint64"},{"internalType":"uint64","name":"balance","type":"uint64"},{"internalType":"bool","name":"exists","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"","type":"string"}],"name":"learners","outputs":[{"internalType":"string","name":"uid","type":"string"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"location","type":"string"},{"internalType":"string","name":"status","type":"string"},{"internalType":"uint64","name":"rating","type":"uint64"},{"internalType":"uint64","name":"balance","type":"uint64"},{"internalType":"bool","name":"exists","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_uid","type":"string"},{"internalType":"uint64","name":"_rating","type":"uint64"}],"name":"updateRating","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"payable","type":"function"}],
    contractAddress : '0xA606E7A8ef0b99f081f674D0DFf2CE90C46cc328'
}

//sendgrid api key
//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